<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ActivityLogTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('activity_log')->delete();
        
        \DB::table('activity_log')->insert(array (
            0 => 
            array (
                'id' => 1,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:44:27',
                'updated_at' => '2022-07-01 00:44:27',
            ),
            1 => 
            array (
                'id' => 2,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:47:11',
                'updated_at' => '2022-07-01 00:47:11',
            ),
            2 => 
            array (
                'id' => 3,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 2,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:47:29',
                'updated_at' => '2022-07-01 00:47:29',
            ),
            3 => 
            array (
                'id' => 4,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 2,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:47:52',
                'updated_at' => '2022-07-01 00:47:52',
            ),
            4 => 
            array (
                'id' => 5,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 2,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:48:08',
                'updated_at' => '2022-07-01 00:48:08',
            ),
            5 => 
            array (
                'id' => 6,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 3,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:48:30',
                'updated_at' => '2022-07-01 00:48:30',
            ),
            6 => 
            array (
                'id' => 7,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 3,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:48:35',
                'updated_at' => '2022-07-01 00:48:35',
            ),
            7 => 
            array (
                'id' => 8,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 4,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:48:44',
                'updated_at' => '2022-07-01 00:48:44',
            ),
            8 => 
            array (
                'id' => 9,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 4,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:48:52',
                'updated_at' => '2022-07-01 00:48:52',
            ),
            9 => 
            array (
                'id' => 10,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 5,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:49:38',
                'updated_at' => '2022-07-01 00:49:38',
            ),
            10 => 
            array (
                'id' => 11,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 5,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:49:57',
                'updated_at' => '2022-07-01 00:49:57',
            ),
            11 => 
            array (
                'id' => 12,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 6,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:50:09',
                'updated_at' => '2022-07-01 00:50:09',
            ),
            12 => 
            array (
                'id' => 13,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 6,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:50:15',
                'updated_at' => '2022-07-01 00:50:15',
            ),
            13 => 
            array (
                'id' => 14,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 7,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:50:28',
                'updated_at' => '2022-07-01 00:50:28',
            ),
            14 => 
            array (
                'id' => 15,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 7,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:50:36',
                'updated_at' => '2022-07-01 00:50:36',
            ),
            15 => 
            array (
                'id' => 16,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 8,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:51:10',
                'updated_at' => '2022-07-01 00:51:10',
            ),
            16 => 
            array (
                'id' => 17,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 8,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 00:51:14',
                'updated_at' => '2022-07-01 00:51:14',
            ),
            17 => 
            array (
                'id' => 18,
                'log_name' => 'default',
                'description' => 'published',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 01:08:05',
                'updated_at' => '2022-07-01 01:08:05',
            ),
            18 => 
            array (
                'id' => 19,
                'log_name' => 'default',
                'description' => 'published',
                'subject_id' => 2,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 02:44:40',
                'updated_at' => '2022-07-01 02:44:40',
            ),
            19 => 
            array (
                'id' => 20,
                'log_name' => 'default',
                'description' => 'published',
                'subject_id' => 3,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 02:44:41',
                'updated_at' => '2022-07-01 02:44:41',
            ),
            20 => 
            array (
                'id' => 21,
                'log_name' => 'default',
                'description' => 'published',
                'subject_id' => 4,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 02:44:43',
                'updated_at' => '2022-07-01 02:44:43',
            ),
            21 => 
            array (
                'id' => 22,
                'log_name' => 'default',
                'description' => 'published',
                'subject_id' => 8,
                'subject_type' => 'App\\Models\\Menu',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 02:44:45',
                'updated_at' => '2022-07-01 02:44:45',
            ),
            22 => 
            array (
                'id' => 23,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\PageHome',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 03:51:58',
                'updated_at' => '2022-07-01 03:51:58',
            ),
            23 => 
            array (
                'id' => 24,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\PageContact',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 03:52:07',
                'updated_at' => '2022-07-01 03:52:07',
            ),
            24 => 
            array (
                'id' => 25,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\PageHome',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 03:52:16',
                'updated_at' => '2022-07-01 03:52:16',
            ),
            25 => 
            array (
                'id' => 26,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\PageHome',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 04:00:27',
                'updated_at' => '2022-07-01 04:00:27',
            ),
            26 => 
            array (
                'id' => 27,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\PageContact',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-01 04:01:32',
                'updated_at' => '2022-07-01 04:01:32',
            ),
            27 => 
            array (
                'id' => 28,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-04 23:11:28',
                'updated_at' => '2022-07-04 23:11:28',
            ),
            28 => 
            array (
                'id' => 29,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 2,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-04 23:11:35',
                'updated_at' => '2022-07-04 23:11:35',
            ),
            29 => 
            array (
                'id' => 30,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 3,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-04 23:11:42',
                'updated_at' => '2022-07-04 23:11:42',
            ),
            30 => 
            array (
                'id' => 31,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 3,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-04 23:11:44',
                'updated_at' => '2022-07-04 23:11:44',
            ),
            31 => 
            array (
                'id' => 32,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Issue',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-04 23:38:00',
                'updated_at' => '2022-07-04 23:38:00',
            ),
            32 => 
            array (
                'id' => 33,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Issue',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-04 23:38:02',
                'updated_at' => '2022-07-04 23:38:02',
            ),
            33 => 
            array (
                'id' => 34,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 2,
                'subject_type' => 'App\\Models\\Issue',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-04 23:38:08',
                'updated_at' => '2022-07-04 23:38:08',
            ),
            34 => 
            array (
                'id' => 35,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 3,
                'subject_type' => 'App\\Models\\Issue',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-04 23:38:18',
                'updated_at' => '2022-07-04 23:38:18',
            ),
            35 => 
            array (
                'id' => 36,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 3,
                'subject_type' => 'App\\Models\\Issue',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-04 23:38:20',
                'updated_at' => '2022-07-04 23:38:20',
            ),
            36 => 
            array (
                'id' => 37,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\IssueArticle',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-04 23:41:25',
                'updated_at' => '2022-07-04 23:41:25',
            ),
            37 => 
            array (
                'id' => 38,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\IssueArticle',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-04 23:41:33',
                'updated_at' => '2022-07-04 23:41:33',
            ),
            38 => 
            array (
                'id' => 39,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 00:30:42',
                'updated_at' => '2022-07-05 00:30:42',
            ),
            39 => 
            array (
                'id' => 40,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 00:30:44',
                'updated_at' => '2022-07-05 00:30:44',
            ),
            40 => 
            array (
                'id' => 41,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 2,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 00:30:49',
                'updated_at' => '2022-07-05 00:30:49',
            ),
            41 => 
            array (
                'id' => 42,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 00:44:47',
                'updated_at' => '2022-07-05 00:44:47',
            ),
            42 => 
            array (
                'id' => 43,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 00:45:38',
                'updated_at' => '2022-07-05 00:45:38',
            ),
            43 => 
            array (
                'id' => 44,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 00:45:55',
                'updated_at' => '2022-07-05 00:45:55',
            ),
            44 => 
            array (
                'id' => 45,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 00:46:17',
                'updated_at' => '2022-07-05 00:46:17',
            ),
            45 => 
            array (
                'id' => 46,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 2,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 00:46:58',
                'updated_at' => '2022-07-05 00:46:58',
            ),
            46 => 
            array (
                'id' => 47,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 3,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 00:47:04',
                'updated_at' => '2022-07-05 00:47:04',
            ),
            47 => 
            array (
                'id' => 48,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 4,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 00:47:13',
                'updated_at' => '2022-07-05 00:47:13',
            ),
            48 => 
            array (
                'id' => 49,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 2,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 00:47:58',
                'updated_at' => '2022-07-05 00:47:58',
            ),
            49 => 
            array (
                'id' => 50,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 3,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 00:48:16',
                'updated_at' => '2022-07-05 00:48:16',
            ),
            50 => 
            array (
                'id' => 51,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 4,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 00:48:25',
                'updated_at' => '2022-07-05 00:48:25',
            ),
            51 => 
            array (
                'id' => 52,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:06:55',
                'updated_at' => '2022-07-05 01:06:55',
            ),
            52 => 
            array (
                'id' => 53,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:06:59',
                'updated_at' => '2022-07-05 01:06:59',
            ),
            53 => 
            array (
                'id' => 54,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:07:35',
                'updated_at' => '2022-07-05 01:07:35',
            ),
            54 => 
            array (
                'id' => 55,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:08:05',
                'updated_at' => '2022-07-05 01:08:05',
            ),
            55 => 
            array (
                'id' => 56,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:23:16',
                'updated_at' => '2022-07-05 01:23:16',
            ),
            56 => 
            array (
                'id' => 57,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 2,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:23:23',
                'updated_at' => '2022-07-05 01:23:23',
            ),
            57 => 
            array (
                'id' => 58,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 3,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:23:30',
                'updated_at' => '2022-07-05 01:23:30',
            ),
            58 => 
            array (
                'id' => 59,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 4,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:23:38',
                'updated_at' => '2022-07-05 01:23:38',
            ),
            59 => 
            array (
                'id' => 60,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 4,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:23:56',
                'updated_at' => '2022-07-05 01:23:56',
            ),
            60 => 
            array (
                'id' => 61,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:24:42',
                'updated_at' => '2022-07-05 01:24:42',
            ),
            61 => 
            array (
                'id' => 62,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:24:49',
                'updated_at' => '2022-07-05 01:24:49',
            ),
            62 => 
            array (
                'id' => 63,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:25:01',
                'updated_at' => '2022-07-05 01:25:01',
            ),
            63 => 
            array (
                'id' => 64,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:26:43',
                'updated_at' => '2022-07-05 01:26:43',
            ),
            64 => 
            array (
                'id' => 65,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 2,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:26:48',
                'updated_at' => '2022-07-05 01:26:48',
            ),
            65 => 
            array (
                'id' => 66,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 2,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:27:18',
                'updated_at' => '2022-07-05 01:27:18',
            ),
            66 => 
            array (
                'id' => 67,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:27:28',
                'updated_at' => '2022-07-05 01:27:28',
            ),
            67 => 
            array (
                'id' => 68,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 2,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:27:33',
                'updated_at' => '2022-07-05 01:27:33',
            ),
            68 => 
            array (
                'id' => 69,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 3,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:27:45',
                'updated_at' => '2022-07-05 01:27:45',
            ),
            69 => 
            array (
                'id' => 70,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 4,
                'subject_type' => 'App\\Models\\Service',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:27:58',
                'updated_at' => '2022-07-05 01:27:58',
            ),
            70 => 
            array (
                'id' => 71,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 1,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:29:10',
                'updated_at' => '2022-07-05 01:29:10',
            ),
            71 => 
            array (
                'id' => 72,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 2,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
            ),
            72 => 
            array (
                'id' => 73,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 3,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:29:31',
                'updated_at' => '2022-07-05 01:29:31',
            ),
            73 => 
            array (
                'id' => 74,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 3,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
            ),
            74 => 
            array (
                'id' => 75,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 4,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:30:04',
                'updated_at' => '2022-07-05 01:30:04',
            ),
            75 => 
            array (
                'id' => 76,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 4,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:30:18',
                'updated_at' => '2022-07-05 01:30:18',
            ),
            76 => 
            array (
                'id' => 77,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 4,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:30:23',
                'updated_at' => '2022-07-05 01:30:23',
            ),
            77 => 
            array (
                'id' => 78,
                'log_name' => 'default',
                'description' => 'created',
                'subject_id' => 5,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:30:32',
                'updated_at' => '2022-07-05 01:30:32',
            ),
            78 => 
            array (
                'id' => 79,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 5,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:31:00',
                'updated_at' => '2022-07-05 01:31:00',
            ),
            79 => 
            array (
                'id' => 80,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_id' => 5,
                'subject_type' => 'App\\Models\\Project',
                'event' => NULL,
                'causer_id' => 1,
                'causer_type' => 'users',
                'properties' => '[]',
                'batch_uuid' => NULL,
                'created_at' => '2022-07-05 01:31:33',
                'updated_at' => '2022-07-05 01:31:33',
            ),
        ));
        
        
    }
}