<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediablesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('mediables')->delete();
        
        \DB::table('mediables')->insert(array (
            0 => 
            array (
                'id' => 55,
                'created_at' => '2022-07-04 22:31:09',
                'updated_at' => '2022-07-04 22:31:09',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 2,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 691,
                'crop_h' => 390,
                'role' => 'company_logo',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            1 => 
            array (
                'id' => 56,
                'created_at' => '2022-07-04 22:31:09',
                'updated_at' => '2022-07-04 22:31:09',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 2,
                'crop_x' => 60,
                'crop_y' => 0,
                'crop_w' => 390,
                'crop_h' => 390,
                'role' => 'company_logo',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            2 => 
            array (
                'id' => 57,
                'created_at' => '2022-07-04 22:31:09',
                'updated_at' => '2022-07-04 22:31:09',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 2,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 1428,
                'crop_h' => 390,
                'role' => 'company_logo',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            3 => 
            array (
                'id' => 58,
                'created_at' => '2022-07-04 22:31:09',
                'updated_at' => '2022-07-04 22:31:09',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 1,
                'crop_x' => 0,
                'crop_y' => 32,
                'crop_w' => 80,
                'crop_h' => 45,
                'role' => 'company_favicon',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            4 => 
            array (
                'id' => 59,
                'created_at' => '2022-07-04 22:31:09',
                'updated_at' => '2022-07-04 22:31:09',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 1,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 78,
                'crop_h' => 78,
                'role' => 'company_favicon',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            5 => 
            array (
                'id' => 60,
                'created_at' => '2022-07-04 22:31:09',
                'updated_at' => '2022-07-04 22:31:09',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 1,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 80,
                'crop_h' => 78,
                'role' => 'company_favicon',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            6 => 
            array (
                'id' => 175,
                'created_at' => '2022-07-05 01:27:45',
                'updated_at' => '2022-07-05 01:27:45',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            7 => 
            array (
                'id' => 176,
                'created_at' => '2022-07-05 01:27:45',
                'updated_at' => '2022-07-05 01:27:45',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            8 => 
            array (
                'id' => 177,
                'created_at' => '2022-07-05 01:27:45',
                'updated_at' => '2022-07-05 01:27:45',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            9 => 
            array (
                'id' => 190,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            10 => 
            array (
                'id' => 191,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            11 => 
            array (
                'id' => 192,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            12 => 
            array (
                'id' => 193,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3997,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            13 => 
            array (
                'id' => 194,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            14 => 
            array (
                'id' => 195,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            15 => 
            array (
                'id' => 196,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            16 => 
            array (
                'id' => 197,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3982,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            17 => 
            array (
                'id' => 198,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            18 => 
            array (
                'id' => 199,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            19 => 
            array (
                'id' => 200,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            20 => 
            array (
                'id' => 201,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            21 => 
            array (
                'id' => 202,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            22 => 
            array (
                'id' => 203,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            23 => 
            array (
                'id' => 204,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            24 => 
            array (
                'id' => 205,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3997,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            25 => 
            array (
                'id' => 206,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            26 => 
            array (
                'id' => 207,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            27 => 
            array (
                'id' => 208,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            28 => 
            array (
                'id' => 209,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3982,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            29 => 
            array (
                'id' => 210,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            30 => 
            array (
                'id' => 211,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            31 => 
            array (
                'id' => 212,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            32 => 
            array (
                'id' => 213,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            33 => 
            array (
                'id' => 262,
                'created_at' => '2022-07-05 02:29:25',
                'updated_at' => '2022-07-05 02:29:25',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            34 => 
            array (
                'id' => 263,
                'created_at' => '2022-07-05 02:29:25',
                'updated_at' => '2022-07-05 02:29:25',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            35 => 
            array (
                'id' => 264,
                'created_at' => '2022-07-05 02:29:25',
                'updated_at' => '2022-07-05 02:29:25',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            36 => 
            array (
                'id' => 265,
                'created_at' => '2022-07-05 02:33:28',
                'updated_at' => '2022-07-05 02:33:28',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            37 => 
            array (
                'id' => 266,
                'created_at' => '2022-07-05 02:33:28',
                'updated_at' => '2022-07-05 02:33:28',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            38 => 
            array (
                'id' => 267,
                'created_at' => '2022-07-05 02:33:28',
                'updated_at' => '2022-07-05 02:33:28',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            39 => 
            array (
                'id' => 298,
                'created_at' => '2022-07-05 03:54:34',
                'updated_at' => '2022-07-05 03:54:34',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\PageHome',
                'media_id' => 6,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 1919,
                'crop_h' => 1080,
                'role' => 'image_a',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            40 => 
            array (
                'id' => 299,
                'created_at' => '2022-07-05 03:54:34',
                'updated_at' => '2022-07-05 03:54:34',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\PageHome',
                'media_id' => 6,
                'crop_x' => 506,
                'crop_y' => 0,
                'crop_w' => 1080,
                'crop_h' => 1080,
                'role' => 'image_a',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            41 => 
            array (
                'id' => 300,
                'created_at' => '2022-07-05 03:54:34',
                'updated_at' => '2022-07-05 03:54:34',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\PageHome',
                'media_id' => 6,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 1919,
                'crop_h' => 1080,
                'role' => 'image_a',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            42 => 
            array (
                'id' => 301,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3997,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            43 => 
            array (
                'id' => 302,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            44 => 
            array (
                'id' => 303,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            45 => 
            array (
                'id' => 304,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            46 => 
            array (
                'id' => 305,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3982,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            47 => 
            array (
                'id' => 306,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            48 => 
            array (
                'id' => 307,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            49 => 
            array (
                'id' => 308,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            50 => 
            array (
                'id' => 309,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            51 => 
            array (
                'id' => 310,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2248,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            52 => 
            array (
                'id' => 311,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3982,
                'crop_h' => 3982,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            53 => 
            array (
                'id' => 312,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3982,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            54 => 
            array (
                'id' => 313,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3997,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            55 => 
            array (
                'id' => 314,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            56 => 
            array (
                'id' => 315,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            57 => 
            array (
                'id' => 316,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            58 => 
            array (
                'id' => 317,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3982,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            59 => 
            array (
                'id' => 318,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            60 => 
            array (
                'id' => 319,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            61 => 
            array (
                'id' => 320,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            62 => 
            array (
                'id' => 321,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            63 => 
            array (
                'id' => 322,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3997,
                'crop_h' => 2248,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            64 => 
            array (
                'id' => 323,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            65 => 
            array (
                'id' => 324,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            66 => 
            array (
                'id' => 325,
                'created_at' => '2022-07-05 04:45:22',
                'updated_at' => '2022-07-05 04:45:22',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3997,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            67 => 
            array (
                'id' => 326,
                'created_at' => '2022-07-05 04:45:22',
                'updated_at' => '2022-07-05 04:45:22',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            68 => 
            array (
                'id' => 327,
                'created_at' => '2022-07-05 04:45:22',
                'updated_at' => '2022-07-05 04:45:22',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            69 => 
            array (
                'id' => 328,
                'created_at' => '2022-07-05 04:45:22',
                'updated_at' => '2022-07-05 04:45:22',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            70 => 
            array (
                'id' => 329,
                'created_at' => '2022-07-05 04:45:22',
                'updated_at' => '2022-07-05 04:45:22',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3982,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            71 => 
            array (
                'id' => 330,
                'created_at' => '2022-07-05 04:45:22',
                'updated_at' => '2022-07-05 04:45:22',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            72 => 
            array (
                'id' => 331,
                'created_at' => '2022-07-05 04:45:22',
                'updated_at' => '2022-07-05 04:45:22',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            73 => 
            array (
                'id' => 332,
                'created_at' => '2022-07-05 04:45:22',
                'updated_at' => '2022-07-05 04:45:22',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            74 => 
            array (
                'id' => 333,
                'created_at' => '2022-07-05 04:45:22',
                'updated_at' => '2022-07-05 04:45:22',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            75 => 
            array (
                'id' => 334,
                'created_at' => '2022-07-05 04:45:22',
                'updated_at' => '2022-07-05 04:45:22',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 7,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 2559,
                'crop_h' => 1440,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            76 => 
            array (
                'id' => 335,
                'created_at' => '2022-07-05 04:45:22',
                'updated_at' => '2022-07-05 04:45:22',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 7,
                'crop_x' => 540,
                'crop_y' => 0,
                'crop_w' => 1440,
                'crop_h' => 1440,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            77 => 
            array (
                'id' => 336,
                'created_at' => '2022-07-05 04:45:22',
                'updated_at' => '2022-07-05 04:45:22',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 7,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 2559,
                'crop_h' => 1440,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
        ));
        
        
    }
}