<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediablesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('mediables')->delete();
        
        \DB::table('mediables')->insert(array (
            0 => 
            array (
                'id' => 55,
                'created_at' => '2022-07-04 22:31:09',
                'updated_at' => '2022-07-04 22:31:09',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 2,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 691,
                'crop_h' => 390,
                'role' => 'company_logo',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            1 => 
            array (
                'id' => 56,
                'created_at' => '2022-07-04 22:31:09',
                'updated_at' => '2022-07-04 22:31:09',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 2,
                'crop_x' => 60,
                'crop_y' => 0,
                'crop_w' => 390,
                'crop_h' => 390,
                'role' => 'company_logo',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            2 => 
            array (
                'id' => 57,
                'created_at' => '2022-07-04 22:31:09',
                'updated_at' => '2022-07-04 22:31:09',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 2,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 1428,
                'crop_h' => 390,
                'role' => 'company_logo',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            3 => 
            array (
                'id' => 58,
                'created_at' => '2022-07-04 22:31:09',
                'updated_at' => '2022-07-04 22:31:09',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 1,
                'crop_x' => 0,
                'crop_y' => 32,
                'crop_w' => 80,
                'crop_h' => 45,
                'role' => 'company_favicon',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            4 => 
            array (
                'id' => 59,
                'created_at' => '2022-07-04 22:31:09',
                'updated_at' => '2022-07-04 22:31:09',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 1,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 78,
                'crop_h' => 78,
                'role' => 'company_favicon',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            5 => 
            array (
                'id' => 60,
                'created_at' => '2022-07-04 22:31:09',
                'updated_at' => '2022-07-04 22:31:09',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 1,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 80,
                'crop_h' => 78,
                'role' => 'company_favicon',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            6 => 
            array (
                'id' => 175,
                'created_at' => '2022-07-05 01:27:45',
                'updated_at' => '2022-07-05 01:27:45',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            7 => 
            array (
                'id' => 176,
                'created_at' => '2022-07-05 01:27:45',
                'updated_at' => '2022-07-05 01:27:45',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            8 => 
            array (
                'id' => 177,
                'created_at' => '2022-07-05 01:27:45',
                'updated_at' => '2022-07-05 01:27:45',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            9 => 
            array (
                'id' => 190,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            10 => 
            array (
                'id' => 191,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            11 => 
            array (
                'id' => 192,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            12 => 
            array (
                'id' => 193,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3997,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            13 => 
            array (
                'id' => 194,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            14 => 
            array (
                'id' => 195,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            15 => 
            array (
                'id' => 196,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            16 => 
            array (
                'id' => 197,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3982,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            17 => 
            array (
                'id' => 198,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            18 => 
            array (
                'id' => 199,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            19 => 
            array (
                'id' => 200,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            20 => 
            array (
                'id' => 201,
                'created_at' => '2022-07-05 01:29:20',
                'updated_at' => '2022-07-05 01:29:20',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            21 => 
            array (
                'id' => 202,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            22 => 
            array (
                'id' => 203,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            23 => 
            array (
                'id' => 204,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            24 => 
            array (
                'id' => 205,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3997,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            25 => 
            array (
                'id' => 206,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            26 => 
            array (
                'id' => 207,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            27 => 
            array (
                'id' => 208,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            28 => 
            array (
                'id' => 209,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3982,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            29 => 
            array (
                'id' => 210,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            30 => 
            array (
                'id' => 211,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            31 => 
            array (
                'id' => 212,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            32 => 
            array (
                'id' => 213,
                'created_at' => '2022-07-05 01:29:55',
                'updated_at' => '2022-07-05 01:29:55',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            33 => 
            array (
                'id' => 262,
                'created_at' => '2022-07-05 02:29:25',
                'updated_at' => '2022-07-05 02:29:25',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            34 => 
            array (
                'id' => 263,
                'created_at' => '2022-07-05 02:29:25',
                'updated_at' => '2022-07-05 02:29:25',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            35 => 
            array (
                'id' => 264,
                'created_at' => '2022-07-05 02:29:25',
                'updated_at' => '2022-07-05 02:29:25',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            36 => 
            array (
                'id' => 265,
                'created_at' => '2022-07-05 02:33:28',
                'updated_at' => '2022-07-05 02:33:28',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            37 => 
            array (
                'id' => 266,
                'created_at' => '2022-07-05 02:33:28',
                'updated_at' => '2022-07-05 02:33:28',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            38 => 
            array (
                'id' => 267,
                'created_at' => '2022-07-05 02:33:28',
                'updated_at' => '2022-07-05 02:33:28',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Service',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            39 => 
            array (
                'id' => 301,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3997,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            40 => 
            array (
                'id' => 302,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            41 => 
            array (
                'id' => 303,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            42 => 
            array (
                'id' => 304,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            43 => 
            array (
                'id' => 305,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3982,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            44 => 
            array (
                'id' => 306,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            45 => 
            array (
                'id' => 307,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            46 => 
            array (
                'id' => 308,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            47 => 
            array (
                'id' => 309,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            48 => 
            array (
                'id' => 310,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2248,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            49 => 
            array (
                'id' => 311,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3982,
                'crop_h' => 3982,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            50 => 
            array (
                'id' => 312,
                'created_at' => '2022-07-05 03:54:50',
                'updated_at' => '2022-07-05 03:54:50',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3982,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            51 => 
            array (
                'id' => 313,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3997,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            52 => 
            array (
                'id' => 314,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            53 => 
            array (
                'id' => 315,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            54 => 
            array (
                'id' => 316,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            55 => 
            array (
                'id' => 317,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3982,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            56 => 
            array (
                'id' => 318,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            57 => 
            array (
                'id' => 319,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            58 => 
            array (
                'id' => 320,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            59 => 
            array (
                'id' => 321,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            60 => 
            array (
                'id' => 322,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3997,
                'crop_h' => 2248,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            61 => 
            array (
                'id' => 323,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            62 => 
            array (
                'id' => 324,
                'created_at' => '2022-07-05 03:54:59',
                'updated_at' => '2022-07-05 03:54:59',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            63 => 
            array (
                'id' => 472,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 22,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 21,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 13,
                'crop_h' => 7,
                'role' => 'icon_phone',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            64 => 
            array (
                'id' => 473,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 22,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 21,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 13,
                'crop_h' => 13,
                'role' => 'icon_phone',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            65 => 
            array (
                'id' => 474,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 22,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 21,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 13,
                'crop_h' => 18,
                'role' => 'icon_phone',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            66 => 
            array (
                'id' => 475,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 23,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 22,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 19,
                'crop_h' => 11,
                'role' => 'icon_envelope',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            67 => 
            array (
                'id' => 476,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 23,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 22,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 12,
                'crop_h' => 12,
                'role' => 'icon_envelope',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            68 => 
            array (
                'id' => 477,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 23,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 22,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 19,
                'crop_h' => 12,
                'role' => 'icon_envelope',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            69 => 
            array (
                'id' => 478,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 24,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 23,
                'crop_x' => 0,
                'crop_y' => 8,
                'crop_w' => 10,
                'crop_h' => 6,
                'role' => 'icon_facebook',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            70 => 
            array (
                'id' => 479,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 24,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 23,
                'crop_x' => 0,
                'crop_y' => 8,
                'crop_w' => 10,
                'crop_h' => 10,
                'role' => 'icon_facebook',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            71 => 
            array (
                'id' => 480,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 24,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 23,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 10,
                'crop_h' => 18,
                'role' => 'icon_facebook',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            72 => 
            array (
                'id' => 481,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 17,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 13,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 29,
                'crop_h' => 16,
                'role' => 'icon_bars',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            73 => 
            array (
                'id' => 482,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 17,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 13,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 22,
                'crop_h' => 22,
                'role' => 'icon_bars',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            74 => 
            array (
                'id' => 483,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 17,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 13,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 29,
                'crop_h' => 22,
                'role' => 'icon_bars',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            75 => 
            array (
                'id' => 484,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 21,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 20,
                'crop_x' => 0,
                'crop_y' => 8,
                'crop_w' => 30,
                'crop_h' => 17,
                'role' => 'icon_xmark',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            76 => 
            array (
                'id' => 485,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 21,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 20,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 30,
                'crop_h' => 30,
                'role' => 'icon_xmark',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            77 => 
            array (
                'id' => 486,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 21,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 20,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 30,
                'crop_h' => 30,
                'role' => 'icon_xmark',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            78 => 
            array (
                'id' => 487,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 18,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 10,
                'crop_x' => 0,
                'crop_y' => 8,
                'crop_w' => 9,
                'crop_h' => 5,
                'role' => 'icon_angle_left',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            79 => 
            array (
                'id' => 488,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 18,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 10,
                'crop_x' => 0,
                'crop_y' => 8,
                'crop_w' => 9,
                'crop_h' => 9,
                'role' => 'icon_angle_left',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            80 => 
            array (
                'id' => 489,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 18,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 10,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 9,
                'crop_h' => 18,
                'role' => 'icon_angle_left',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            81 => 
            array (
                'id' => 490,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 19,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 11,
                'crop_x' => 0,
                'crop_y' => 8,
                'crop_w' => 9,
                'crop_h' => 5,
                'role' => 'icon_angle_right',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            82 => 
            array (
                'id' => 491,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 19,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 11,
                'crop_x' => 0,
                'crop_y' => 8,
                'crop_w' => 9,
                'crop_h' => 9,
                'role' => 'icon_angle_right',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            83 => 
            array (
                'id' => 492,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 19,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 11,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 9,
                'crop_h' => 18,
                'role' => 'icon_angle_right',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            84 => 
            array (
                'id' => 493,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 20,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 12,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 16,
                'crop_h' => 9,
                'role' => 'icon_angle_up',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            85 => 
            array (
                'id' => 494,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 20,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 12,
                'crop_x' => 8,
                'crop_y' => 0,
                'crop_w' => 9,
                'crop_h' => 9,
                'role' => 'icon_angle_up',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            86 => 
            array (
                'id' => 495,
                'created_at' => '2022-07-05 05:59:07',
                'updated_at' => '2022-07-05 05:59:07',
                'deleted_at' => NULL,
                'mediable_id' => 20,
                'mediable_type' => 'A17\\Twill\\Models\\Setting',
                'media_id' => 12,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 18,
                'crop_h' => 9,
                'role' => 'icon_angle_up',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            87 => 
            array (
                'id' => 499,
                'created_at' => '2022-07-05 07:06:24',
                'updated_at' => '2022-07-05 07:06:24',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\PageHome',
                'media_id' => 6,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 1919,
                'crop_h' => 1080,
                'role' => 'image_a',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            88 => 
            array (
                'id' => 500,
                'created_at' => '2022-07-05 07:06:24',
                'updated_at' => '2022-07-05 07:06:24',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\PageHome',
                'media_id' => 6,
                'crop_x' => 506,
                'crop_y' => 0,
                'crop_w' => 1080,
                'crop_h' => 1080,
                'role' => 'image_a',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            89 => 
            array (
                'id' => 501,
                'created_at' => '2022-07-05 07:06:24',
                'updated_at' => '2022-07-05 07:06:24',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\PageHome',
                'media_id' => 6,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 1919,
                'crop_h' => 1080,
                'role' => 'image_a',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            90 => 
            array (
                'id' => 514,
                'created_at' => '2022-07-05 22:29:40',
                'updated_at' => '2022-07-05 22:29:40',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 7,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 2559,
                'crop_h' => 1440,
                'role' => 'featured_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            91 => 
            array (
                'id' => 515,
                'created_at' => '2022-07-05 22:29:40',
                'updated_at' => '2022-07-05 22:29:40',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 7,
                'crop_x' => 540,
                'crop_y' => 0,
                'crop_w' => 1440,
                'crop_h' => 1440,
                'role' => 'featured_image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            92 => 
            array (
                'id' => 516,
                'created_at' => '2022-07-05 22:29:40',
                'updated_at' => '2022-07-05 22:29:40',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 7,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 2559,
                'crop_h' => 1440,
                'role' => 'featured_image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            93 => 
            array (
                'id' => 517,
                'created_at' => '2022-07-05 22:29:40',
                'updated_at' => '2022-07-05 22:29:40',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3997,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            94 => 
            array (
                'id' => 518,
                'created_at' => '2022-07-05 22:29:40',
                'updated_at' => '2022-07-05 22:29:40',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            95 => 
            array (
                'id' => 519,
                'created_at' => '2022-07-05 22:29:40',
                'updated_at' => '2022-07-05 22:29:40',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3997,
                'crop_h' => 3997,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            96 => 
            array (
                'id' => 520,
                'created_at' => '2022-07-05 22:29:40',
                'updated_at' => '2022-07-05 22:29:40',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2248,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            97 => 
            array (
                'id' => 521,
                'created_at' => '2022-07-05 22:29:40',
                'updated_at' => '2022-07-05 22:29:40',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3982,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            98 => 
            array (
                'id' => 522,
                'created_at' => '2022-07-05 22:29:40',
                'updated_at' => '2022-07-05 22:29:40',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3982,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            99 => 
            array (
                'id' => 523,
                'created_at' => '2022-07-05 22:29:40',
                'updated_at' => '2022-07-05 22:29:40',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 499,
                'crop_w' => 3998,
                'crop_h' => 2249,
                'role' => 'images',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            100 => 
            array (
                'id' => 524,
                'created_at' => '2022-07-05 22:29:40',
                'updated_at' => '2022-07-05 22:29:40',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            101 => 
            array (
                'id' => 525,
                'created_at' => '2022-07-05 22:29:40',
                'updated_at' => '2022-07-05 22:29:40',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3998,
                'crop_h' => 3998,
                'role' => 'images',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            102 => 
            array (
                'id' => 526,
                'created_at' => '2022-07-05 23:10:16',
                'updated_at' => '2022-07-05 23:10:16',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\PageAbout',
                'media_id' => 24,
                'crop_x' => 0,
                'crop_y' => 72,
                'crop_w' => 3456,
                'crop_h' => 1944,
                'role' => 'image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'default',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            103 => 
            array (
                'id' => 527,
                'created_at' => '2022-07-05 23:10:16',
                'updated_at' => '2022-07-05 23:10:16',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\PageAbout',
                'media_id' => 24,
                'crop_x' => 216,
                'crop_y' => 0,
                'crop_w' => 2304,
                'crop_h' => 2304,
                'role' => 'image',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
            104 => 
            array (
                'id' => 528,
                'created_at' => '2022-07-05 23:10:16',
                'updated_at' => '2022-07-05 23:10:16',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\PageAbout',
                'media_id' => 24,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 3456,
                'crop_h' => 2304,
                'role' => 'image',
                'crop' => 'flexible',
                'lqip_data' => NULL,
                'ratio' => 'free',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
                'locale' => 'en',
            ),
        ));
        
        
    }
}