<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProjectSlugsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('project_slugs')->delete();
        
        \DB::table('project_slugs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'project_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:26:57',
                'slug' => 'project-a',
                'locale' => 'en',
                'active' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'project_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:26:57',
                'slug' => 'project-a1',
                'locale' => 'en',
                'active' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'project_id' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:27:15',
                'slug' => 'project-a2',
                'locale' => 'en',
                'active' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'project_id' => 3,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-14 01:42:50',
                'slug' => 'project-a3',
                'locale' => 'en',
                'active' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'project_id' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:28:26',
                'slug' => 'project-b1',
                'locale' => 'en',
                'active' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'project_id' => 5,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:28:34',
                'slug' => 'project-c1',
                'locale' => 'en',
                'active' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'project_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:26:57',
                'slug' => 'philson-terrace-browns-bay',
                'locale' => 'en',
                'active' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'project_id' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:27:15',
                'slug' => 'clayburn-road-gend-eden',
                'locale' => 'en',
                'active' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'project_id' => 3,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-14 01:42:50',
                'slug' => 'edmonton-residence-development',
                'locale' => 'en',
                'active' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'project_id' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:28:26',
                'slug' => 'beach-road-browns-bay',
                'locale' => 'en',
                'active' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'project_id' => 5,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:28:34',
                'slug' => 'marriott-road-pakuranga-heights',
                'locale' => 'en',
                'active' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'project_id' => 6,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:28:44',
                'slug' => 'springbank-lane-te-atatu-peninsula',
                'locale' => 'en',
                'active' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'project_id' => 7,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:29:02',
                'slug' => 'yeovil-road-te-atatu-peninsula',
                'locale' => 'en',
                'active' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'project_id' => 8,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:29:13',
                'slug' => 'princes-street-west-pukekohe',
                'locale' => 'en',
                'active' => 0,
            ),
            14 => 
            array (
                'id' => 15,
                'project_id' => 9,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:29:20',
                'slug' => 'rangeview-road-sunnyvale',
                'locale' => 'en',
                'active' => 0,
            ),
            15 => 
            array (
                'id' => 16,
                'project_id' => 10,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:29:35',
                'slug' => 'sorrel-crescent-half-moon-bay',
                'locale' => 'en',
                'active' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'project_id' => 11,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:29:46',
                'slug' => 'patons-road-howick',
                'locale' => 'en',
                'active' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'project_id' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:29:54',
                'slug' => 'elliot-street-papakura',
                'locale' => 'en',
                'active' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'project_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:01',
                'slug' => 'archibald-road-kelston',
                'locale' => 'en',
                'active' => 0,
            ),
            19 => 
            array (
                'id' => 20,
                'project_id' => 14,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:09',
                'slug' => 'yeovil-road-te-atatu-peninsula-2',
                'locale' => 'en',
                'active' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'project_id' => 15,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:19',
                'slug' => 'te-atatu-road-te-atatu-south',
                'locale' => 'en',
                'active' => 0,
            ),
            21 => 
            array (
                'id' => 22,
                'project_id' => 16,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:27',
                'slug' => 'jillian-drive-ranui',
                'locale' => 'en',
                'active' => 0,
            ),
            22 => 
            array (
                'id' => 23,
                'project_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:35',
                'slug' => 'hamlin-road-mount-wellington',
                'locale' => 'en',
                'active' => 0,
            ),
            23 => 
            array (
                'id' => 24,
                'project_id' => 18,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:43',
                'slug' => 'geordie-street-henderson',
                'locale' => 'en',
                'active' => 0,
            ),
            24 => 
            array (
                'id' => 25,
                'project_id' => 19,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:50',
                'slug' => 'fonteyn-street-avondale',
                'locale' => 'en',
                'active' => 0,
            ),
            25 => 
            array (
                'id' => 26,
                'project_id' => 20,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:58',
                'slug' => 'titirangi-road-new-lynn',
                'locale' => 'en',
                'active' => 0,
            ),
            26 => 
            array (
                'id' => 27,
                'project_id' => 21,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:31:05',
                'slug' => 'victoria-street-pukekohe',
                'locale' => 'en',
                'active' => 0,
            ),
            27 => 
            array (
                'id' => 28,
                'project_id' => 22,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:31:12',
                'slug' => 'hepper-street-new-lynn',
                'locale' => 'en',
                'active' => 0,
            ),
            28 => 
            array (
                'id' => 29,
                'project_id' => 23,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:31:21',
                'slug' => 'sturdee-road-manurewa',
                'locale' => 'en',
                'active' => 0,
            ),
            29 => 
            array (
                'id' => 30,
                'project_id' => 24,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:31:29',
                'slug' => 'quibray-place-botany-downs',
                'locale' => 'en',
                'active' => 0,
            ),
            30 => 
            array (
                'id' => 31,
                'project_id' => 25,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:31:36',
                'slug' => 'west-street-pukekohe',
                'locale' => 'en',
                'active' => 0,
            ),
            31 => 
            array (
                'id' => 32,
                'project_id' => 26,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:31:43',
                'slug' => 'brickworks-bay-road-hobsonville',
                'locale' => 'en',
                'active' => 0,
            ),
            32 => 
            array (
                'id' => 33,
                'project_id' => 27,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:31:50',
                'slug' => 'montmere-avenue-te-atatu',
                'locale' => 'en',
                'active' => 0,
            ),
            33 => 
            array (
                'id' => 34,
                'project_id' => 28,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:32:01',
                'slug' => 'pakuranga-road-pakuranga',
                'locale' => 'en',
                'active' => 0,
            ),
            34 => 
            array (
                'id' => 35,
                'project_id' => 29,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:32:18',
                'slug' => 'george-street-papakura',
                'locale' => 'en',
                'active' => 0,
            ),
            35 => 
            array (
                'id' => 36,
                'project_id' => 30,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:32:38',
                'slug' => 'mandarin-place-highland-park',
                'locale' => 'en',
                'active' => 0,
            ),
            36 => 
            array (
                'id' => 37,
                'project_id' => 31,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:32:45',
                'slug' => '70-merton-road-st-johns',
                'locale' => 'en',
                'active' => 0,
            ),
            37 => 
            array (
                'id' => 38,
                'project_id' => 32,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:32:59',
                'slug' => 'great-north-road-new-lynn',
                'locale' => 'en',
                'active' => 0,
            ),
            38 => 
            array (
                'id' => 39,
                'project_id' => 33,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:33:07',
                'slug' => 'walker-road-pt-chevalier',
                'locale' => 'en',
                'active' => 0,
            ),
            39 => 
            array (
                'id' => 40,
                'project_id' => 34,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:33:17',
                'slug' => 'taikata-road-te-atatu-peninsula',
                'locale' => 'en',
                'active' => 0,
            ),
            40 => 
            array (
                'id' => 41,
                'project_id' => 35,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:33:27',
                'slug' => 'shirley-road-papatoetoe',
                'locale' => 'en',
                'active' => 0,
            ),
            41 => 
            array (
                'id' => 42,
                'project_id' => 36,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:33:39',
                'slug' => 'massey-road-mangere',
                'locale' => 'en',
                'active' => 0,
            ),
            42 => 
            array (
                'id' => 43,
                'project_id' => 37,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:33:50',
                'slug' => 'gloucester-road-manurewa',
                'locale' => 'en',
                'active' => 0,
            ),
            43 => 
            array (
                'id' => 44,
                'project_id' => 38,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:34:00',
                'slug' => 'riverview-road-new-lynn',
                'locale' => 'en',
                'active' => 0,
            ),
            44 => 
            array (
                'id' => 45,
                'project_id' => 39,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:34:11',
                'slug' => 'dellwood-avenue-henderson',
                'locale' => 'en',
                'active' => 0,
            ),
            45 => 
            array (
                'id' => 46,
                'project_id' => 40,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:34:25',
                'slug' => 'taikata-road-te-atatu-peninsula-2',
                'locale' => 'en',
                'active' => 0,
            ),
            46 => 
            array (
                'id' => 47,
                'project_id' => 41,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:34:44',
                'slug' => 'beach-road-te-atatu-peninsula',
                'locale' => 'en',
                'active' => 0,
            ),
            47 => 
            array (
                'id' => 48,
                'project_id' => 42,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-11 21:48:44',
                'slug' => 'beach-haven-road',
                'locale' => 'en',
                'active' => 1,
            ),
            48 => 
            array (
                'id' => 49,
                'project_id' => 43,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:35:00',
                'slug' => 'glenhaven-place-te-atatu-peninsula',
                'locale' => 'en',
                'active' => 0,
            ),
            49 => 
            array (
                'id' => 50,
                'project_id' => 44,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:35:09',
                'slug' => 'ribblesdale-road-henderson',
                'locale' => 'en',
                'active' => 0,
            ),
            50 => 
            array (
                'id' => 51,
                'project_id' => 45,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:35:21',
                'slug' => 'fairdene-avenue-henderson',
                'locale' => 'en',
                'active' => 0,
            ),
            51 => 
            array (
                'id' => 52,
                'project_id' => 46,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:35:36',
                'slug' => 'woodford-avenue-henderson',
                'locale' => 'en',
                'active' => 0,
            ),
            52 => 
            array (
                'id' => 53,
                'project_id' => 47,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:35:46',
                'slug' => 'shoreham-street-avondale',
                'locale' => 'en',
                'active' => 0,
            ),
            53 => 
            array (
                'id' => 54,
                'project_id' => 48,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:35:54',
                'slug' => 'mahia-road-manurewa',
                'locale' => 'en',
                'active' => 0,
            ),
            54 => 
            array (
                'id' => 55,
                'project_id' => 49,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:36:02',
                'slug' => 'jayne-place-torbay',
                'locale' => 'en',
                'active' => 0,
            ),
            55 => 
            array (
                'id' => 56,
                'project_id' => 50,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:36:10',
                'slug' => 'richards-avenue-forrest-hill',
                'locale' => 'en',
                'active' => 0,
            ),
            56 => 
            array (
                'id' => 57,
                'project_id' => 51,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:36:20',
                'slug' => 'takapu-street-henderson',
                'locale' => 'en',
                'active' => 0,
            ),
            57 => 
            array (
                'id' => 58,
                'project_id' => 52,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:36:33',
                'slug' => 'blyton-lane-pakuranga-heights',
                'locale' => 'en',
                'active' => 0,
            ),
            58 => 
            array (
                'id' => 59,
                'project_id' => 53,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:36:43',
                'slug' => 'moire-road-massey',
                'locale' => 'en',
                'active' => 0,
            ),
            59 => 
            array (
                'id' => 60,
                'project_id' => 54,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:36:57',
                'slug' => 'pakuranga-road-pakuranga-2',
                'locale' => 'en',
                'active' => 0,
            ),
            60 => 
            array (
                'id' => 61,
                'project_id' => 55,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:37:05',
                'slug' => 'berwyn-avenue-takanini',
                'locale' => 'en',
                'active' => 0,
            ),
            61 => 
            array (
                'id' => 62,
                'project_id' => 56,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:37:20',
                'slug' => 'lavelle-road-henderson',
                'locale' => 'en',
                'active' => 0,
            ),
            62 => 
            array (
                'id' => 63,
                'project_id' => 57,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:37:30',
                'slug' => 'enderby-drive-te-atatu-peninsula',
                'locale' => 'en',
                'active' => 0,
            ),
            63 => 
            array (
                'id' => 64,
                'project_id' => 58,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:37:40',
                'slug' => 'abbotleigh-avenue-te-atatu-peninsula',
                'locale' => 'en',
                'active' => 0,
            ),
            64 => 
            array (
                'id' => 65,
                'project_id' => 59,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:37:49',
                'slug' => 'jolson-road-mount-wellington',
                'locale' => 'en',
                'active' => 0,
            ),
            65 => 
            array (
                'id' => 66,
                'project_id' => 60,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:37:58',
                'slug' => 'edgewater-drive-pakuranga',
                'locale' => 'en',
                'active' => 0,
            ),
            66 => 
            array (
                'id' => 67,
                'project_id' => 61,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:38:07',
                'slug' => 'rehia-road-massey',
                'locale' => 'en',
                'active' => 0,
            ),
            67 => 
            array (
                'id' => 68,
                'project_id' => 62,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:38:18',
                'slug' => 'royal-road-massey',
                'locale' => 'en',
                'active' => 0,
            ),
            68 => 
            array (
                'id' => 69,
                'project_id' => 63,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:38:25',
                'slug' => 'forrest-hill-road-milford',
                'locale' => 'en',
                'active' => 0,
            ),
            69 => 
            array (
                'id' => 70,
                'project_id' => 64,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:38:33',
                'slug' => 'tarawera-terrace-st-heliers',
                'locale' => 'en',
                'active' => 0,
            ),
            70 => 
            array (
                'id' => 71,
                'project_id' => 65,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:38:43',
                'slug' => 'camphora-place-ranui',
                'locale' => 'en',
                'active' => 0,
            ),
            71 => 
            array (
                'id' => 72,
                'project_id' => 66,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:38:51',
                'slug' => 'methuen-road-new-windsor',
                'locale' => 'en',
                'active' => 0,
            ),
            72 => 
            array (
                'id' => 73,
                'project_id' => 67,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:39:01',
                'slug' => 'ellesmere-crescent-pakuranga-heights',
                'locale' => 'en',
                'active' => 0,
            ),
            73 => 
            array (
                'id' => 74,
                'project_id' => 68,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:39:09',
                'slug' => 'allender-drive-torbay',
                'locale' => 'en',
                'active' => 0,
            ),
            74 => 
            array (
                'id' => 75,
                'project_id' => 69,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:39:25',
                'slug' => 'evelyn-place-hillcrest',
                'locale' => 'en',
                'active' => 0,
            ),
            75 => 
            array (
                'id' => 76,
                'project_id' => 70,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:39:34',
                'slug' => 'edwards-avenue-henderson',
                'locale' => 'en',
                'active' => 0,
            ),
            76 => 
            array (
                'id' => 77,
                'project_id' => 71,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:39:41',
                'slug' => 'stanley-road-glenfield',
                'locale' => 'en',
                'active' => 0,
            ),
            77 => 
            array (
                'id' => 78,
                'project_id' => 72,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:39:49',
                'slug' => 'regia-close-half-moon-bay',
                'locale' => 'en',
                'active' => 0,
            ),
            78 => 
            array (
                'id' => 79,
                'project_id' => 73,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:39:55',
                'slug' => 'donovan-avenue-massey',
                'locale' => 'en',
                'active' => 0,
            ),
            79 => 
            array (
                'id' => 80,
                'project_id' => 74,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:40:02',
                'slug' => 'fjord-way-hingaia',
                'locale' => 'en',
                'active' => 0,
            ),
            80 => 
            array (
                'id' => 81,
                'project_id' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:27:15',
                'slug' => 'clayburn-road-glen-eden',
                'locale' => 'en',
                'active' => 0,
            ),
            81 => 
            array (
                'id' => 82,
                'project_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:26:57',
                'slug' => 'philson-terrace',
                'locale' => 'en',
                'active' => 1,
            ),
            82 => 
            array (
                'id' => 83,
                'project_id' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:27:15',
                'slug' => 'clayburn-road',
                'locale' => 'en',
                'active' => 1,
            ),
            83 => 
            array (
                'id' => 84,
                'project_id' => 3,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-14 01:42:50',
                'slug' => 'edmonton-road',
                'locale' => 'en',
                'active' => 1,
            ),
            84 => 
            array (
                'id' => 85,
                'project_id' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:28:26',
                'slug' => 'beach-road',
                'locale' => 'en',
                'active' => 1,
            ),
            85 => 
            array (
                'id' => 86,
                'project_id' => 5,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:28:34',
                'slug' => 'marriott-road',
                'locale' => 'en',
                'active' => 1,
            ),
            86 => 
            array (
                'id' => 87,
                'project_id' => 6,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:28:44',
                'slug' => 'springbank-lane',
                'locale' => 'en',
                'active' => 1,
            ),
            87 => 
            array (
                'id' => 88,
                'project_id' => 7,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:29:02',
                'slug' => 'yeovil-road',
                'locale' => 'en',
                'active' => 1,
            ),
            88 => 
            array (
                'id' => 89,
                'project_id' => 8,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:29:13',
                'slug' => 'princes-street',
                'locale' => 'en',
                'active' => 1,
            ),
            89 => 
            array (
                'id' => 90,
                'project_id' => 9,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:29:20',
                'slug' => 'rangeview-road',
                'locale' => 'en',
                'active' => 1,
            ),
            90 => 
            array (
                'id' => 91,
                'project_id' => 10,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:29:35',
                'slug' => 'sorrel-crescent',
                'locale' => 'en',
                'active' => 1,
            ),
            91 => 
            array (
                'id' => 92,
                'project_id' => 11,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:29:46',
                'slug' => 'patons-road',
                'locale' => 'en',
                'active' => 1,
            ),
            92 => 
            array (
                'id' => 93,
                'project_id' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:29:54',
                'slug' => 'elliot-street',
                'locale' => 'en',
                'active' => 1,
            ),
            93 => 
            array (
                'id' => 94,
                'project_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:01',
                'slug' => 'archibald-road',
                'locale' => 'en',
                'active' => 1,
            ),
            94 => 
            array (
                'id' => 95,
                'project_id' => 14,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:09',
                'slug' => 'yeovil-road-2',
                'locale' => 'en',
                'active' => 1,
            ),
            95 => 
            array (
                'id' => 96,
                'project_id' => 15,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:19',
                'slug' => 'te-atatu-road',
                'locale' => 'en',
                'active' => 1,
            ),
            96 => 
            array (
                'id' => 97,
                'project_id' => 16,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:27',
                'slug' => 'jillian-drive',
                'locale' => 'en',
                'active' => 1,
            ),
            97 => 
            array (
                'id' => 98,
                'project_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:35',
                'slug' => 'hamlin-road',
                'locale' => 'en',
                'active' => 1,
            ),
            98 => 
            array (
                'id' => 99,
                'project_id' => 18,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:43',
                'slug' => 'geordie-street',
                'locale' => 'en',
                'active' => 1,
            ),
            99 => 
            array (
                'id' => 100,
                'project_id' => 19,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:50',
                'slug' => 'fonteyn-street',
                'locale' => 'en',
                'active' => 1,
            ),
            100 => 
            array (
                'id' => 101,
                'project_id' => 20,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:30:58',
                'slug' => 'titirangi-road',
                'locale' => 'en',
                'active' => 1,
            ),
            101 => 
            array (
                'id' => 102,
                'project_id' => 21,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:31:05',
                'slug' => 'victoria-street',
                'locale' => 'en',
                'active' => 1,
            ),
            102 => 
            array (
                'id' => 103,
                'project_id' => 22,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:31:12',
                'slug' => 'hepper-street',
                'locale' => 'en',
                'active' => 1,
            ),
            103 => 
            array (
                'id' => 104,
                'project_id' => 23,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:31:21',
                'slug' => 'sturdee-road',
                'locale' => 'en',
                'active' => 1,
            ),
            104 => 
            array (
                'id' => 105,
                'project_id' => 24,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:31:29',
                'slug' => 'quibray-place',
                'locale' => 'en',
                'active' => 1,
            ),
            105 => 
            array (
                'id' => 106,
                'project_id' => 25,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:31:36',
                'slug' => 'west-street',
                'locale' => 'en',
                'active' => 1,
            ),
            106 => 
            array (
                'id' => 107,
                'project_id' => 26,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:31:43',
                'slug' => 'brickworks-bay-road',
                'locale' => 'en',
                'active' => 1,
            ),
            107 => 
            array (
                'id' => 108,
                'project_id' => 27,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:31:50',
                'slug' => 'montmere-avenue',
                'locale' => 'en',
                'active' => 1,
            ),
            108 => 
            array (
                'id' => 109,
                'project_id' => 28,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:32:01',
                'slug' => 'pakuranga-road',
                'locale' => 'en',
                'active' => 1,
            ),
            109 => 
            array (
                'id' => 110,
                'project_id' => 29,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:32:18',
                'slug' => 'george-street',
                'locale' => 'en',
                'active' => 1,
            ),
            110 => 
            array (
                'id' => 111,
                'project_id' => 30,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:32:38',
                'slug' => 'mandarin-place',
                'locale' => 'en',
                'active' => 1,
            ),
            111 => 
            array (
                'id' => 112,
                'project_id' => 31,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:32:45',
                'slug' => '70-merton-road',
                'locale' => 'en',
                'active' => 1,
            ),
            112 => 
            array (
                'id' => 113,
                'project_id' => 32,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:32:59',
                'slug' => 'great-north-road',
                'locale' => 'en',
                'active' => 1,
            ),
            113 => 
            array (
                'id' => 114,
                'project_id' => 33,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:33:07',
                'slug' => 'walker-road',
                'locale' => 'en',
                'active' => 1,
            ),
            114 => 
            array (
                'id' => 115,
                'project_id' => 34,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:33:17',
                'slug' => 'taikata-road',
                'locale' => 'en',
                'active' => 1,
            ),
            115 => 
            array (
                'id' => 116,
                'project_id' => 35,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:33:27',
                'slug' => 'shirley-road',
                'locale' => 'en',
                'active' => 1,
            ),
            116 => 
            array (
                'id' => 117,
                'project_id' => 36,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:33:39',
                'slug' => 'massey-road',
                'locale' => 'en',
                'active' => 1,
            ),
            117 => 
            array (
                'id' => 118,
                'project_id' => 37,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:33:50',
                'slug' => 'gloucester-road',
                'locale' => 'en',
                'active' => 1,
            ),
            118 => 
            array (
                'id' => 119,
                'project_id' => 38,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:34:00',
                'slug' => 'riverview-road',
                'locale' => 'en',
                'active' => 1,
            ),
            119 => 
            array (
                'id' => 120,
                'project_id' => 39,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:34:11',
                'slug' => 'dellwood-avenue',
                'locale' => 'en',
                'active' => 1,
            ),
            120 => 
            array (
                'id' => 121,
                'project_id' => 40,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:34:25',
                'slug' => 'taikata-road-2',
                'locale' => 'en',
                'active' => 1,
            ),
            121 => 
            array (
                'id' => 122,
                'project_id' => 41,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:34:44',
                'slug' => 'beach-road-2',
                'locale' => 'en',
                'active' => 1,
            ),
            122 => 
            array (
                'id' => 123,
                'project_id' => 43,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:35:00',
                'slug' => 'glenhaven-place',
                'locale' => 'en',
                'active' => 1,
            ),
            123 => 
            array (
                'id' => 124,
                'project_id' => 44,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:35:09',
                'slug' => 'ribblesdale-road',
                'locale' => 'en',
                'active' => 1,
            ),
            124 => 
            array (
                'id' => 125,
                'project_id' => 45,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:35:21',
                'slug' => 'fairdene-avenue',
                'locale' => 'en',
                'active' => 1,
            ),
            125 => 
            array (
                'id' => 126,
                'project_id' => 46,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:35:36',
                'slug' => 'woodford-avenue',
                'locale' => 'en',
                'active' => 1,
            ),
            126 => 
            array (
                'id' => 127,
                'project_id' => 47,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:35:46',
                'slug' => 'shoreham-street',
                'locale' => 'en',
                'active' => 1,
            ),
            127 => 
            array (
                'id' => 128,
                'project_id' => 48,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:35:54',
                'slug' => 'mahia-road',
                'locale' => 'en',
                'active' => 1,
            ),
            128 => 
            array (
                'id' => 129,
                'project_id' => 49,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:36:02',
                'slug' => 'jayne-place',
                'locale' => 'en',
                'active' => 1,
            ),
            129 => 
            array (
                'id' => 130,
                'project_id' => 50,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:36:10',
                'slug' => 'richards-avenue',
                'locale' => 'en',
                'active' => 1,
            ),
            130 => 
            array (
                'id' => 131,
                'project_id' => 51,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:36:20',
                'slug' => 'takapu-street',
                'locale' => 'en',
                'active' => 1,
            ),
            131 => 
            array (
                'id' => 132,
                'project_id' => 52,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:36:33',
                'slug' => 'blyton-lane',
                'locale' => 'en',
                'active' => 1,
            ),
            132 => 
            array (
                'id' => 133,
                'project_id' => 53,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:36:43',
                'slug' => 'moire-road',
                'locale' => 'en',
                'active' => 1,
            ),
            133 => 
            array (
                'id' => 134,
                'project_id' => 54,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:36:57',
                'slug' => 'pakuranga-road-2',
                'locale' => 'en',
                'active' => 1,
            ),
            134 => 
            array (
                'id' => 135,
                'project_id' => 55,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:37:05',
                'slug' => 'berwyn-avenue',
                'locale' => 'en',
                'active' => 1,
            ),
            135 => 
            array (
                'id' => 136,
                'project_id' => 56,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:37:20',
                'slug' => 'lavelle-road',
                'locale' => 'en',
                'active' => 1,
            ),
            136 => 
            array (
                'id' => 137,
                'project_id' => 57,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:37:30',
                'slug' => 'enderby-drive',
                'locale' => 'en',
                'active' => 1,
            ),
            137 => 
            array (
                'id' => 138,
                'project_id' => 58,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:37:40',
                'slug' => 'abbotleigh-avenue',
                'locale' => 'en',
                'active' => 1,
            ),
            138 => 
            array (
                'id' => 139,
                'project_id' => 59,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:37:49',
                'slug' => 'jolson-road',
                'locale' => 'en',
                'active' => 1,
            ),
            139 => 
            array (
                'id' => 140,
                'project_id' => 60,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:37:58',
                'slug' => 'edgewater-drive',
                'locale' => 'en',
                'active' => 1,
            ),
            140 => 
            array (
                'id' => 141,
                'project_id' => 61,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:38:07',
                'slug' => 'rehia-road',
                'locale' => 'en',
                'active' => 1,
            ),
            141 => 
            array (
                'id' => 142,
                'project_id' => 62,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:38:18',
                'slug' => 'royal-road',
                'locale' => 'en',
                'active' => 1,
            ),
            142 => 
            array (
                'id' => 143,
                'project_id' => 63,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:38:25',
                'slug' => 'forrest-hill-road',
                'locale' => 'en',
                'active' => 1,
            ),
            143 => 
            array (
                'id' => 144,
                'project_id' => 64,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:38:33',
                'slug' => 'tarawera-terrace',
                'locale' => 'en',
                'active' => 1,
            ),
            144 => 
            array (
                'id' => 145,
                'project_id' => 65,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:38:43',
                'slug' => 'camphora-place',
                'locale' => 'en',
                'active' => 1,
            ),
            145 => 
            array (
                'id' => 146,
                'project_id' => 66,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:38:51',
                'slug' => 'methuen-road',
                'locale' => 'en',
                'active' => 1,
            ),
            146 => 
            array (
                'id' => 147,
                'project_id' => 67,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:39:01',
                'slug' => 'ellesmere-crescent',
                'locale' => 'en',
                'active' => 1,
            ),
            147 => 
            array (
                'id' => 148,
                'project_id' => 68,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:39:09',
                'slug' => 'allender-drive',
                'locale' => 'en',
                'active' => 1,
            ),
            148 => 
            array (
                'id' => 149,
                'project_id' => 69,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:39:25',
                'slug' => 'evelyn-place',
                'locale' => 'en',
                'active' => 1,
            ),
            149 => 
            array (
                'id' => 150,
                'project_id' => 70,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:39:34',
                'slug' => 'edwards-avenue',
                'locale' => 'en',
                'active' => 1,
            ),
            150 => 
            array (
                'id' => 151,
                'project_id' => 71,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:39:41',
                'slug' => 'stanley-road',
                'locale' => 'en',
                'active' => 1,
            ),
            151 => 
            array (
                'id' => 152,
                'project_id' => 72,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:39:49',
                'slug' => 'regia-close',
                'locale' => 'en',
                'active' => 1,
            ),
            152 => 
            array (
                'id' => 153,
                'project_id' => 73,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:39:55',
                'slug' => 'donovan-avenue',
                'locale' => 'en',
                'active' => 1,
            ),
            153 => 
            array (
                'id' => 154,
                'project_id' => 74,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-07-13 11:40:02',
                'slug' => 'fjord-way',
                'locale' => 'en',
                'active' => 1,
            ),
        ));
        
        
    }
}