<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProjectsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('projects')->delete();
        
        \DB::table('projects')->insert(array (
            0 => 
            array (
                'id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-07-05 01:06:55',
                'updated_at' => '2022-07-13 11:26:57',
                'published' => 1,
                'title' => 'Philson Terrace',
                'description' => 'Browns Bay',
                'position' => 1,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2022-07-05 01:26:48',
                'updated_at' => '2022-07-13 11:27:15',
                'published' => 1,
                'title' => 'Clayburn Road',
                'description' => 'Glen Eden',
                'position' => 2,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-07-05 01:29:31',
                'updated_at' => '2022-07-14 01:42:50',
                'published' => 1,
                'title' => 'Edmonton Road',
                'description' => 'Henderson',
                'position' => 3,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'deleted_at' => NULL,
                'created_at' => '2022-07-05 01:30:04',
                'updated_at' => '2022-07-13 11:28:26',
                'published' => 1,
                'title' => 'Beach Road',
                'description' => 'Browns Bay',
                'position' => 4,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'deleted_at' => NULL,
                'created_at' => '2022-07-05 01:30:32',
                'updated_at' => '2022-07-13 11:28:34',
                'published' => 1,
                'title' => 'Marriott Road',
                'description' => 'Pakuranga Heights',
                'position' => 5,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'deleted_at' => NULL,
                'created_at' => '2022-07-08 03:30:43',
                'updated_at' => '2022-07-13 11:28:44',
                'published' => 1,
                'title' => 'Springbank Lane',
                'description' => 'Te Atatu Peninsula',
                'position' => 6,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'deleted_at' => NULL,
                'created_at' => '2022-07-08 03:31:58',
                'updated_at' => '2022-07-13 11:29:02',
                'published' => 1,
                'title' => 'Yeovil Road',
                'description' => 'Te Atatu Peninsula',
                'position' => 7,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'deleted_at' => NULL,
                'created_at' => '2022-07-08 03:32:38',
                'updated_at' => '2022-07-13 11:29:13',
                'published' => 1,
                'title' => 'Princes Street',
                'description' => 'West Pukekohe',
                'position' => 8,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'deleted_at' => NULL,
                'created_at' => '2022-07-08 03:33:18',
                'updated_at' => '2022-07-13 11:29:20',
                'published' => 1,
                'title' => 'Rangeview Road',
                'description' => 'Sunnyvale',
                'position' => 9,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'deleted_at' => NULL,
                'created_at' => '2022-07-08 03:34:16',
                'updated_at' => '2022-07-13 11:29:35',
                'published' => 1,
                'title' => 'Sorrel Crescent',
                'description' => 'Half Moon Bay',
                'position' => 10,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:24:30',
                'updated_at' => '2022-07-13 11:29:46',
                'published' => 1,
                'title' => 'Patons Road',
                'description' => 'Howick',
                'position' => 11,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:25:51',
                'updated_at' => '2022-07-13 11:29:54',
                'published' => 1,
                'title' => 'Elliot Street',
                'description' => 'Papakura',
                'position' => 12,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:26:02',
                'updated_at' => '2022-07-13 11:30:01',
                'published' => 1,
                'title' => 'Archibald Road',
                'description' => 'Kelston',
                'position' => 13,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:26:47',
                'updated_at' => '2022-07-13 11:30:09',
                'published' => 1,
                'title' => 'Yeovil Road',
                'description' => 'Te Atatu Peninsula',
                'position' => 14,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:29:49',
                'updated_at' => '2022-07-13 11:30:19',
                'published' => 1,
                'title' => 'Te Atatu Road',
                'description' => 'Te Atatu South',
                'position' => 15,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:30:40',
                'updated_at' => '2022-07-13 11:30:27',
                'published' => 1,
                'title' => 'Jillian Drive',
                'description' => 'Ranui',
                'position' => 16,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:30:52',
                'updated_at' => '2022-07-13 11:30:35',
                'published' => 1,
                'title' => 'Hamlin Road',
                'description' => 'Mount Wellington',
                'position' => 17,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:31:07',
                'updated_at' => '2022-07-13 11:30:43',
                'published' => 1,
                'title' => 'Geordie Street',
                'description' => 'Henderson',
                'position' => 18,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:31:13',
                'updated_at' => '2022-07-13 11:30:50',
                'published' => 1,
                'title' => 'Fonteyn Street',
                'description' => 'Avondale',
                'position' => 19,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:31:21',
                'updated_at' => '2022-07-13 11:30:58',
                'published' => 1,
                'title' => 'Titirangi Road',
                'description' => 'New Lynn',
                'position' => 20,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:31:28',
                'updated_at' => '2022-07-13 11:31:05',
                'published' => 1,
                'title' => 'Victoria Street',
                'description' => 'Pukekohe',
                'position' => 21,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:31:38',
                'updated_at' => '2022-07-13 11:31:12',
                'published' => 1,
                'title' => 'Hepper Street',
                'description' => 'New Lynn',
                'position' => 22,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:31:55',
                'updated_at' => '2022-07-13 11:31:21',
                'published' => 1,
                'title' => 'Sturdee Road',
                'description' => 'Manurewa',
                'position' => 23,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:32:05',
                'updated_at' => '2022-07-13 11:31:29',
                'published' => 1,
                'title' => 'Quibray Place',
                'description' => 'Botany Downs',
                'position' => 24,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:32:13',
                'updated_at' => '2022-07-13 11:31:36',
                'published' => 1,
                'title' => 'West Street',
                'description' => 'Pukekohe',
                'position' => 25,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:37:28',
                'updated_at' => '2022-07-13 11:31:43',
                'published' => 1,
                'title' => 'Brickworks Bay Road',
                'description' => 'Hobsonville',
                'position' => 26,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:37:51',
                'updated_at' => '2022-07-13 11:31:50',
                'published' => 1,
                'title' => 'Montmere Avenue',
                'description' => 'Te Atatu',
                'position' => 27,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:38:01',
                'updated_at' => '2022-07-13 11:32:01',
                'published' => 1,
                'title' => 'Pakuranga Road',
                'description' => 'Pakuranga',
                'position' => 28,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:38:07',
                'updated_at' => '2022-07-13 11:32:18',
                'published' => 1,
                'title' => 'George Street',
                'description' => 'Papakura',
                'position' => 29,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:38:26',
                'updated_at' => '2022-07-13 11:32:38',
                'published' => 1,
                'title' => 'Mandarin Place',
                'description' => 'Highland Park',
                'position' => 30,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:38:34',
                'updated_at' => '2022-07-13 11:32:45',
                'published' => 1,
                'title' => '70 Merton Road',
                'description' => 'St Johns',
                'position' => 31,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:38:41',
                'updated_at' => '2022-07-13 11:32:59',
                'published' => 1,
                'title' => 'Great North Road',
                'description' => 'New Lynn',
                'position' => 32,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:38:48',
                'updated_at' => '2022-07-13 11:33:07',
                'published' => 1,
                'title' => 'Walker Road',
                'description' => 'Pt Chevalier',
                'position' => 33,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:39:01',
                'updated_at' => '2022-07-13 11:33:17',
                'published' => 1,
                'title' => 'Taikata Road',
                'description' => 'Te Atatu Peninsula',
                'position' => 34,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:39:09',
                'updated_at' => '2022-07-13 11:33:27',
                'published' => 1,
                'title' => 'Shirley Road',
                'description' => 'Papatoetoe',
                'position' => 35,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:39:33',
                'updated_at' => '2022-07-13 11:33:39',
                'published' => 1,
                'title' => 'Massey Road',
                'description' => 'Mangere',
                'position' => 36,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:39:44',
                'updated_at' => '2022-07-13 11:33:50',
                'published' => 1,
                'title' => 'Gloucester Road',
                'description' => 'Manurewa',
                'position' => 37,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:39:54',
                'updated_at' => '2022-07-13 11:34:00',
                'published' => 1,
                'title' => 'Riverview Road',
                'description' => 'New Lynn',
                'position' => 38,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:40:02',
                'updated_at' => '2022-07-13 11:34:11',
                'published' => 1,
                'title' => 'Dellwood Avenue',
                'description' => 'Henderson',
                'position' => 39,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:40:15',
                'updated_at' => '2022-07-13 11:34:25',
                'published' => 1,
                'title' => 'Taikata Road',
                'description' => 'Te Atatu Peninsula',
                'position' => 40,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:40:26',
                'updated_at' => '2022-07-13 11:34:44',
                'published' => 1,
                'title' => 'Beach Road',
                'description' => 'Te Atatu Peninsula',
                'position' => 41,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:40:32',
                'updated_at' => '2022-07-11 21:48:44',
                'published' => 1,
                'title' => 'Beach Haven Road',
                'description' => 'Beach Haven Road',
                'position' => 42,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:40:44',
                'updated_at' => '2022-07-13 11:35:00',
                'published' => 1,
                'title' => 'Glenhaven Place',
                'description' => 'Te Atatu Peninsula',
                'position' => 43,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:40:56',
                'updated_at' => '2022-07-13 11:35:09',
                'published' => 1,
                'title' => 'Ribblesdale Road',
                'description' => 'Henderson',
                'position' => 44,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:41:04',
                'updated_at' => '2022-07-13 11:35:21',
                'published' => 1,
                'title' => 'Fairdene Avenue',
                'description' => 'Henderson',
                'position' => 45,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:41:13',
                'updated_at' => '2022-07-13 11:35:36',
                'published' => 1,
                'title' => 'Woodford Avenue',
                'description' => 'Henderson',
                'position' => 46,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:41:20',
                'updated_at' => '2022-07-13 11:35:46',
                'published' => 1,
                'title' => 'Shoreham Street',
                'description' => 'Avondale',
                'position' => 47,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:41:32',
                'updated_at' => '2022-07-13 11:35:54',
                'published' => 1,
                'title' => 'Mahia Road',
                'description' => 'Manurewa',
                'position' => 48,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:41:38',
                'updated_at' => '2022-07-13 11:36:02',
                'published' => 1,
                'title' => 'Jayne Place',
                'description' => 'Torbay',
                'position' => 49,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:41:49',
                'updated_at' => '2022-07-13 11:36:10',
                'published' => 1,
                'title' => 'Richards Avenue',
                'description' => 'Forrest Hill',
                'position' => 50,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:41:56',
                'updated_at' => '2022-07-13 11:36:20',
                'published' => 1,
                'title' => 'Takapu Street',
                'description' => 'Henderson',
                'position' => 51,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:42:09',
                'updated_at' => '2022-07-13 11:36:33',
                'published' => 1,
                'title' => 'Blyton Lane',
                'description' => 'Pakuranga Heights',
                'position' => 52,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:42:48',
                'updated_at' => '2022-07-13 11:36:43',
                'published' => 1,
                'title' => 'Moire Road',
                'description' => 'Massey',
                'position' => 53,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:43:00',
                'updated_at' => '2022-07-13 11:36:57',
                'published' => 1,
                'title' => 'Pakuranga Road',
                'description' => 'Pakuranga',
                'position' => 54,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:43:18',
                'updated_at' => '2022-07-13 11:37:05',
                'published' => 1,
                'title' => 'Berwyn Avenue',
                'description' => 'Takanini',
                'position' => 55,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:43:27',
                'updated_at' => '2022-07-13 11:37:20',
                'published' => 1,
                'title' => 'Lavelle Road',
                'description' => 'Henderson',
                'position' => 56,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:43:39',
                'updated_at' => '2022-07-13 11:37:30',
                'published' => 1,
                'title' => 'Enderby Drive',
                'description' => 'Te Atatu Peninsula',
                'position' => 57,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:44:05',
                'updated_at' => '2022-07-13 11:37:40',
                'published' => 1,
                'title' => 'Abbotleigh Avenue',
                'description' => 'Te Atatu Peninsula',
                'position' => 58,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:44:22',
                'updated_at' => '2022-07-13 11:37:49',
                'published' => 1,
                'title' => 'Jolson Road',
                'description' => 'Mount Wellington',
                'position' => 59,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:44:32',
                'updated_at' => '2022-07-13 11:37:57',
                'published' => 1,
                'title' => 'Edgewater Drive',
                'description' => 'Pakuranga',
                'position' => 60,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:44:42',
                'updated_at' => '2022-07-13 11:38:07',
                'published' => 1,
                'title' => 'Rehia Road',
                'description' => 'Massey',
                'position' => 61,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:44:49',
                'updated_at' => '2022-07-13 11:38:18',
                'published' => 1,
                'title' => 'Royal Road',
                'description' => 'Massey',
                'position' => 62,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:44:56',
                'updated_at' => '2022-07-13 11:38:25',
                'published' => 1,
                'title' => 'Forrest Hill Road',
                'description' => 'Milford',
                'position' => 63,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:45:08',
                'updated_at' => '2022-07-13 11:38:33',
                'published' => 1,
                'title' => 'Tarawera Terrace',
                'description' => 'St Heliers',
                'position' => 64,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:45:15',
                'updated_at' => '2022-07-13 11:38:43',
                'published' => 1,
                'title' => 'Camphora Place',
                'description' => 'Ranui',
                'position' => 65,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:53:36',
                'updated_at' => '2022-07-13 11:38:51',
                'published' => 1,
                'title' => 'Methuen Road',
                'description' => 'New Windsor',
                'position' => 66,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:54:02',
                'updated_at' => '2022-07-13 11:39:00',
                'published' => 1,
                'title' => 'Ellesmere Crescent',
                'description' => 'Pakuranga Heights',
                'position' => 67,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:54:12',
                'updated_at' => '2022-07-13 11:39:09',
                'published' => 1,
                'title' => 'Allender Drive',
                'description' => 'Torbay',
                'position' => 68,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:54:21',
                'updated_at' => '2022-07-13 11:39:25',
                'published' => 1,
                'title' => 'Evelyn Place',
                'description' => 'Hillcrest',
                'position' => 69,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:54:28',
                'updated_at' => '2022-07-13 11:39:34',
                'published' => 1,
                'title' => 'Edwards Avenue',
                'description' => 'Henderson',
                'position' => 70,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:54:35',
                'updated_at' => '2022-07-13 11:39:41',
                'published' => 1,
                'title' => 'Stanley Road',
                'description' => 'Glenfield',
                'position' => 71,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:54:43',
                'updated_at' => '2022-07-13 11:39:49',
                'published' => 1,
                'title' => 'Regia Close',
                'description' => 'Half Moon Bay',
                'position' => 72,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:54:51',
                'updated_at' => '2022-07-13 11:39:55',
                'published' => 1,
                'title' => 'Donovan Avenue',
                'description' => 'Massey',
                'position' => 73,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'deleted_at' => NULL,
                'created_at' => '2022-07-11 20:54:59',
                'updated_at' => '2022-07-13 11:40:02',
                'published' => 1,
                'title' => 'Fjord Way',
                'description' => 'Hingaia',
                'position' => 74,
                'location' => NULL,
                'year' => NULL,
                'client' => NULL,
            ),
        ));
        
        
    }
}